name: Construir Pulguita IA

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Descargar proyecto
        uses: actions/checkout@v4

      - name: Compilar APK
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer android debug
          workdir: .

      - name: Subir APK
        uses: actions/upload-artifact@v4
        with:
          name: Pulguita-IA-APK
          path: ${{ steps.buildozer.outputs.filename }}
